load 'environment.rb'
require 'rake'
task :download do
  BaumgartnerDataset.new(true).download
end

task :prepare do
  BaumgartnerDataset.new(true).prepare
end

task :full_test_run, [:strftime, :percentile] do |t, args|
  args[:percentile] = args[:percentile]
  BaumgartnerDataset.new.download_and_prepare
  BaumgartnerDataset.new.store_sliced_transitions(args[:strftime], args[:percentile].to_f)
  BaumgartnerDataset.new.analyze_sliced_transitions(args[:strftime], args[:percentile].to_f)
end

task :full_live_run, [:strftime, :percentile] do |t, args|
  args[:percentile] = args[:percentile].to_f
  BaumgartnerDataset.new(true).download_and_prepare
  BaumgartnerDataset.new(true).store_sliced_transitions(args[:strftime], args[:percentile].to_f)
  BaumgartnerDataset.new(true).analyze_sliced_transitions(strftime_str, percentile)
end